export interface CheatSheet {
  title: string;
  name: string;
  path: string;
  description: string;
  category: string;
  icon: string;
  themeColor: string;
  canonical: string;
  keywords: string[];
  features: string[];
  ogImage: string;
  twitterImage: string;
  variationOf?: string;
  datePublished?: string;
  softwareVersion?: string;
}

export const CHEATSHEETS_CONFIG: Record<string, CheatSheet> = {
  // HTML-based cheatsheets from md_html directory
  "kubernetes": {
    title: "Kubernetes Cheatsheet | Online Free DevTools",
    name: "Kubernetes",
    path: "/freedevtools/c/kubernetes/",
    description: "Quick reference for Kubernetes commands and concepts.",
    category: "Developer Cheatsheets",
    icon: "☸️",
    themeColor: "#326ce5",
    canonical: "https://hexmos.com/freedevtools/c/kubernetes/",
    keywords: ["kubernetes", "k8s", "container orchestration", "cheatsheet"],
    features: ["Kubernetes commands", "Resource management", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "python": {
    title: "Python Cheatsheet | Online Free DevTools",
    name: "Python",
    path: "/freedevtools/c/python/",
    description: "Quick reference for Python programming language.",
    category: "Developer Cheatsheets",
    icon: "🐍",
    themeColor: "#3776ab",
    canonical: "https://hexmos.com/freedevtools/c/python/",
    keywords: ["python", "programming", "cheatsheet", "reference"],
    features: ["Python syntax", "Common patterns", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "golang": {
    title: "Go Cheatsheet | Online Free DevTools",
    name: "Go",
    path: "/freedevtools/c/golang/",
    description: "Quick reference for Go programming language.",
    category: "Developer Cheatsheets",
    icon: "🐹",
    themeColor: "#00add8",
    canonical: "https://hexmos.com/freedevtools/c/golang/",
    keywords: ["golang", "go", "programming", "cheatsheet"],
    features: ["Go syntax", "Common patterns", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "java": {
    title: "Java Cheatsheet | Online Free DevTools",
    name: "Java",
    path: "/freedevtools/c/java/",
    description: "Quick reference for Java programming language.",
    category: "Developer Cheatsheets",
    icon: "☕",
    themeColor: "#ed8b00",
    canonical: "https://hexmos.com/freedevtools/c/java/",
    keywords: ["java", "programming", "cheatsheet", "reference"],
    features: ["Java syntax", "Common patterns", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "vscode": {
    title: "VS Code Cheatsheet | Online Free DevTools",
    name: "VS Code",
    path: "/freedevtools/c/vscode/",
    description: "Quick reference for Visual Studio Code shortcuts and features.",
    category: "Developer Cheatsheets",
    icon: "💻",
    themeColor: "#007acc",
    canonical: "https://hexmos.com/freedevtools/c/vscode/",
    keywords: ["vscode", "visual studio code", "shortcuts", "cheatsheet"],
    features: ["Keyboard shortcuts", "Extensions", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "emmet": {
    title: "Emmet Cheatsheet | Online Free DevTools",
    name: "Emmet",
    path: "/freedevtools/c/emmet/",
    description: "Quick reference for Emmet HTML/CSS shortcuts.",
    category: "Developer Cheatsheets",
    icon: "⚡",
    themeColor: "#1a1a1a",
    canonical: "https://hexmos.com/freedevtools/c/emmet/",
    keywords: ["emmet", "html", "css", "shortcuts", "cheatsheet"],
    features: ["HTML shortcuts", "CSS shortcuts", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "gcp": {
    title: "Google Cloud Platform Cheatsheet | Online Free DevTools",
    name: "Google Cloud Platform",
    path: "/freedevtools/c/gcp/",
    description: "Quick reference for Google Cloud Platform services and commands.",
    category: "Developer Cheatsheets",
    icon: "☁️",
    themeColor: "#4285f4",
    canonical: "https://hexmos.com/freedevtools/c/gcp/",
    keywords: ["gcp", "google cloud", "cloud computing", "cheatsheet"],
    features: ["GCP services", "CLI commands", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "firebase_cli": {
    title: "Firebase CLI Cheatsheet | Online Free DevTools",
    name: "Firebase CLI",
    path: "/freedevtools/c/firebase_cli/",
    description: "Quick reference for Firebase CLI commands.",
    category: "Developer Cheatsheets",
    icon: "🔥",
    themeColor: "#ffca28",
    canonical: "https://hexmos.com/freedevtools/c/firebase_cli/",
    keywords: ["firebase", "cli", "commands", "cheatsheet"],
    features: ["Firebase CLI commands", "Deployment", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "sublime_text": {
    title: "Sublime Text Cheatsheet | Online Free DevTools",
    name: "Sublime Text",
    path: "/freedevtools/c/sublime_text/",
    description: "Quick reference for Sublime Text shortcuts and features.",
    category: "Developer Cheatsheets",
    icon: "📝",
    themeColor: "#ff9800",
    canonical: "https://hexmos.com/freedevtools/c/sublime_text/",
    keywords: ["sublime text", "editor", "shortcuts", "cheatsheet"],
    features: ["Keyboard shortcuts", "Features", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "XML": {
    title: "XML Cheatsheet | Online Free DevTools",
    name: "XML",
    path: "/freedevtools/c/XML/",
    description: "Quick reference for XML syntax and structure.",
    category: "Developer Cheatsheets",
    icon: "📄",
    themeColor: "#ff6600",
    canonical: "https://hexmos.com/freedevtools/c/XML/",
    keywords: ["xml", "markup", "syntax", "cheatsheet"],
    features: ["XML syntax", "Structure", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "adonis": {
    title: "AdonisJS Cheatsheet | Online Free DevTools",
    name: "AdonisJS",
    path: "/freedevtools/c/adonis/",
    description: "Quick reference for AdonisJS framework commands and concepts.",
    category: "Developer Cheatsheets",
    icon: "🚀",
    themeColor: "#5a45ff",
    canonical: "https://hexmos.com/freedevtools/c/adonis/",
    keywords: ["adonisjs", "nodejs", "framework", "cheatsheet"],
    features: ["AdonisJS commands", "Framework concepts", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "angular": {
    title: "Angular Cheatsheet | Online Free DevTools",
    name: "Angular",
    path: "/freedevtools/c/angular/",
    description: "Quick reference for Angular framework commands and concepts.",
    category: "Developer Cheatsheets",
    icon: "🅰️",
    themeColor: "#dd0031",
    canonical: "https://hexmos.com/freedevtools/c/angular/",
    keywords: ["angular", "typescript", "framework", "cheatsheet"],
    features: ["Angular CLI", "Components", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "angularjs": {
    title: "AngularJS Cheatsheet | Online Free DevTools",
    name: "AngularJS",
    path: "/freedevtools/c/angularjs/",
    description: "Quick reference for AngularJS framework commands and concepts.",
    category: "Developer Cheatsheets",
    icon: "🅰️",
    themeColor: "#e23237",
    canonical: "https://hexmos.com/freedevtools/c/angularjs/",
    keywords: ["angularjs", "javascript", "framework", "cheatsheet"],
    features: ["AngularJS directives", "Services", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "aws": {
    title: "AWS Cheatsheet | Online Free DevTools",
    name: "AWS",
    path: "/freedevtools/c/aws/",
    description: "Quick reference for Amazon Web Services commands and concepts.",
    category: "Developer Cheatsheets",
    icon: "☁️",
    themeColor: "#ff9900",
    canonical: "https://hexmos.com/freedevtools/c/aws/",
    keywords: ["aws", "amazon web services", "cloud", "cheatsheet"],
    features: ["AWS CLI", "Services", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "bash": {
    title: "Bash Cheatsheet | Online Free DevTools",
    name: "Bash",
    path: "/freedevtools/c/bash/",
    description: "Quick reference for Bash shell commands and scripting.",
    category: "Developer Cheatsheets",
    icon: "🐚",
    themeColor: "#4eaa25",
    canonical: "https://hexmos.com/freedevtools/c/bash/",
    keywords: ["bash", "shell", "scripting", "cheatsheet"],
    features: ["Bash commands", "Scripting", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "C": {
    title: "C Programming Cheatsheet | Online Free DevTools",
    name: "C",
    path: "/freedevtools/c/C/",
    description: "Quick reference for C programming language syntax and concepts.",
    category: "Developer Cheatsheets",
    icon: "🔧",
    themeColor: "#00599c",
    canonical: "https://hexmos.com/freedevtools/c/C/",
    keywords: ["c", "programming", "syntax", "cheatsheet"],
    features: ["C syntax", "Pointers", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "C#": {
    title: "C# Cheatsheet | Online Free DevTools",
    name: "C#",
    path: "/freedevtools/c/C#/",
    description: "Quick reference for C# programming language syntax and concepts.",
    category: "Developer Cheatsheets",
    icon: "🔷",
    themeColor: "#239120",
    canonical: "https://hexmos.com/freedevtools/c/C#/",
    keywords: ["csharp", "c#", "programming", "cheatsheet"],
    features: ["C# syntax", ".NET", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "commitlint.config": {
    title: "Commitlint Config Cheatsheet | Online Free DevTools",
    name: "Commitlint Config",
    path: "/freedevtools/c/commitlint.config/",
    description: "Quick reference for Commitlint configuration and rules.",
    category: "Developer Cheatsheets",
    icon: "📝",
    themeColor: "#000000",
    canonical: "https://hexmos.com/freedevtools/c/commitlint.config/",
    keywords: ["commitlint", "git", "configuration", "cheatsheet"],
    features: ["Commit rules", "Configuration", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "css3": {
    title: "CSS3 Cheatsheet | Online Free DevTools",
    name: "CSS3",
    path: "/freedevtools/c/css3/",
    description: "Quick reference for CSS3 properties and selectors.",
    category: "Developer Cheatsheets",
    icon: "🎨",
    themeColor: "#1572b6",
    canonical: "https://hexmos.com/freedevtools/c/css3/",
    keywords: ["css3", "styling", "web development", "cheatsheet"],
    features: ["CSS3 properties", "Selectors", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "curl": {
    title: "cURL Cheatsheet | Online Free DevTools",
    name: "cURL",
    path: "/freedevtools/c/curl/",
    description: "Quick reference for cURL command-line tool.",
    category: "Developer Cheatsheets",
    icon: "🌐",
    themeColor: "#073551",
    canonical: "https://hexmos.com/freedevtools/c/curl/",
    keywords: ["curl", "http", "api", "cheatsheet"],
    features: ["HTTP requests", "API testing", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "django": {
    title: "Django Cheatsheet | Online Free DevTools",
    name: "Django",
    path: "/freedevtools/c/django/",
    description: "Quick reference for Django web framework commands and concepts.",
    category: "Developer Cheatsheets",
    icon: "🐍",
    themeColor: "#092e20",
    canonical: "https://hexmos.com/freedevtools/c/django/",
    keywords: ["django", "python", "web framework", "cheatsheet"],
    features: ["Django commands", "Models", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "docker": {
    title: "Docker Cheatsheet | Online Free DevTools",
    name: "Docker",
    path: "/freedevtools/c/docker/",
    description: "Quick reference for Docker containerization commands.",
    category: "Developer Cheatsheets",
    icon: "🐳",
    themeColor: "#2496ed",
    canonical: "https://hexmos.com/freedevtools/c/docker/",
    keywords: ["docker", "containers", "devops", "cheatsheet"],
    features: ["Docker commands", "Containerization", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "drush": {
    title: "Drush Cheatsheet | Online Free DevTools",
    name: "Drush",
    path: "/freedevtools/c/drush/",
    description: "Quick reference for Drush Drupal command-line tool.",
    category: "Developer Cheatsheets",
    icon: "🌿",
    themeColor: "#0678be",
    canonical: "https://hexmos.com/freedevtools/c/drush/",
    keywords: ["drush", "drupal", "cms", "cheatsheet"],
    features: ["Drupal commands", "CMS management", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "elasticsearch": {
    title: "Elasticsearch Cheatsheet | Online Free DevTools",
    name: "Elasticsearch",
    path: "/freedevtools/c/elasticsearch/",
    description: "Quick reference for Elasticsearch search engine commands.",
    category: "Developer Cheatsheets",
    icon: "🔍",
    themeColor: "#005571",
    canonical: "https://hexmos.com/freedevtools/c/elasticsearch/",
    keywords: ["elasticsearch", "search", "database", "cheatsheet"],
    features: ["Search queries", "Indexing", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "ember": {
    title: "Ember.js Cheatsheet | Online Free DevTools",
    name: "Ember.js",
    path: "/freedevtools/c/ember/",
    description: "Quick reference for Ember.js framework commands and concepts.",
    category: "Developer Cheatsheets",
    icon: "🟠",
    themeColor: "#e04e39",
    canonical: "https://hexmos.com/freedevtools/c/ember/",
    keywords: ["ember", "javascript", "framework", "cheatsheet"],
    features: ["Ember CLI", "Components", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "express": {
    title: "Express.js Cheatsheet | Online Free DevTools",
    name: "Express.js",
    path: "/freedevtools/c/express/",
    description: "Quick reference for Express.js web framework commands.",
    category: "Developer Cheatsheets",
    icon: "🚂",
    themeColor: "#000000",
    canonical: "https://hexmos.com/freedevtools/c/express/",
    keywords: ["express", "nodejs", "web framework", "cheatsheet"],
    features: ["Express commands", "Middleware", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "feathers": {
    title: "Feathers.js Cheatsheet | Online Free DevTools",
    name: "Feathers.js",
    path: "/freedevtools/c/feathers/",
    description: "Quick reference for Feathers.js framework commands.",
    category: "Developer Cheatsheets",
    icon: "🪶",
    themeColor: "#333333",
    canonical: "https://hexmos.com/freedevtools/c/feathers/",
    keywords: ["feathers", "nodejs", "api", "cheatsheet"],
    features: ["API generation", "Services", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "git": {
    title: "Git Cheatsheet | Online Free DevTools",
    name: "Git",
    path: "/freedevtools/c/git/",
    description: "Quick reference for Git version control commands.",
    category: "Developer Cheatsheets",
    icon: "📚",
    themeColor: "#f05032",
    canonical: "https://hexmos.com/freedevtools/c/git/",
    keywords: ["git", "version control", "vcs", "cheatsheet"],
    features: ["Git commands", "Branching", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "heroku": {
    title: "Heroku Cheatsheet | Online Free DevTools",
    name: "Heroku",
    path: "/freedevtools/c/heroku/",
    description: "Quick reference for Heroku cloud platform commands.",
    category: "Developer Cheatsheets",
    icon: "🟣",
    themeColor: "#430098",
    canonical: "https://hexmos.com/freedevtools/c/heroku/",
    keywords: ["heroku", "cloud", "deployment", "cheatsheet"],
    features: ["Heroku CLI", "Deployment", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "html5": {
    title: "HTML5 Cheatsheet | Online Free DevTools",
    name: "HTML5",
    path: "/freedevtools/c/html5/",
    description: "Quick reference for HTML5 elements and attributes.",
    category: "Developer Cheatsheets",
    icon: "🌐",
    themeColor: "#e34f26",
    canonical: "https://hexmos.com/freedevtools/c/html5/",
    keywords: ["html5", "markup", "web development", "cheatsheet"],
    features: ["HTML5 elements", "Semantic tags", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "javascript": {
    title: "JavaScript Cheatsheet | Online Free DevTools",
    name: "JavaScript",
    path: "/freedevtools/c/javascript/",
    description: "Quick reference for JavaScript programming language.",
    category: "Developer Cheatsheets",
    icon: "🟨",
    themeColor: "#f7df1e",
    canonical: "https://hexmos.com/freedevtools/c/javascript/",
    keywords: ["javascript", "js", "programming", "cheatsheet"],
    features: ["JavaScript syntax", "ES6+", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "laravel": {
    title: "Laravel Cheatsheet | Online Free DevTools",
    name: "Laravel",
    path: "/freedevtools/c/laravel/",
    description: "Quick reference for Laravel PHP framework commands.",
    category: "Developer Cheatsheets",
    icon: "🔴",
    themeColor: "#ff2d20",
    canonical: "https://hexmos.com/freedevtools/c/laravel/",
    keywords: ["laravel", "php", "web framework", "cheatsheet"],
    features: ["Artisan commands", "Eloquent", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "macos": {
    title: "macOS Cheatsheet | Online Free DevTools",
    name: "macOS",
    path: "/freedevtools/c/macos/",
    description: "Quick reference for macOS terminal commands and shortcuts.",
    category: "Developer Cheatsheets",
    icon: "🍎",
    themeColor: "#000000",
    canonical: "https://hexmos.com/freedevtools/c/macos/",
    keywords: ["macos", "terminal", "shortcuts", "cheatsheet"],
    features: ["Terminal commands", "Keyboard shortcuts", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "moleculer": {
    title: "Moleculer Cheatsheet | Online Free DevTools",
    name: "Moleculer",
    path: "/freedevtools/c/moleculer/",
    description: "Quick reference for Moleculer microservices framework.",
    category: "Developer Cheatsheets",
    icon: "⚛️",
    themeColor: "#3eaf7c",
    canonical: "https://hexmos.com/freedevtools/c/moleculer/",
    keywords: ["moleculer", "microservices", "nodejs", "cheatsheet"],
    features: ["Microservices", "Service discovery", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "mongodb": {
    title: "MongoDB Cheatsheet | Online Free DevTools",
    name: "MongoDB",
    path: "/freedevtools/c/mongodb/",
    description: "Quick reference for MongoDB database commands and queries.",
    category: "Developer Cheatsheets",
    icon: "🍃",
    themeColor: "#47a248",
    canonical: "https://hexmos.com/freedevtools/c/mongodb/",
    keywords: ["mongodb", "database", "nosql", "cheatsheet"],
    features: ["MongoDB queries", "Aggregation", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "mysql": {
    title: "MySQL Cheatsheet | Online Free DevTools",
    name: "MySQL",
    path: "/freedevtools/c/mysql/",
    description: "Quick reference for MySQL database commands and queries.",
    category: "Developer Cheatsheets",
    icon: "🐬",
    themeColor: "#4479a1",
    canonical: "https://hexmos.com/freedevtools/c/mysql/",
    keywords: ["mysql", "database", "sql", "cheatsheet"],
    features: ["SQL queries", "Database management", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "nanobox_boxfile": {
    title: "Nanobox Boxfile Cheatsheet | Online Free DevTools",
    name: "Nanobox Boxfile",
    path: "/freedevtools/c/nanobox_boxfile/",
    description: "Quick reference for Nanobox Boxfile configuration.",
    category: "Developer Cheatsheets",
    icon: "📦",
    themeColor: "#00d4aa",
    canonical: "https://hexmos.com/freedevtools/c/nanobox_boxfile/",
    keywords: ["nanobox", "deployment", "configuration", "cheatsheet"],
    features: ["Boxfile config", "Deployment", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "nanobox_cli": {
    title: "Nanobox CLI Cheatsheet | Online Free DevTools",
    name: "Nanobox CLI",
    path: "/freedevtools/c/nanobox_cli/",
    description: "Quick reference for Nanobox CLI commands.",
    category: "Developer Cheatsheets",
    icon: "📦",
    themeColor: "#00d4aa",
    canonical: "https://hexmos.com/freedevtools/c/nanobox_cli/",
    keywords: ["nanobox", "cli", "deployment", "cheatsheet"],
    features: ["CLI commands", "Deployment", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "nginx": {
    title: "Nginx Cheatsheet | Online Free DevTools",
    name: "Nginx",
    path: "/freedevtools/c/nginx/",
    description: "Quick reference for Nginx web server configuration.",
    category: "Developer Cheatsheets",
    icon: "🌐",
    themeColor: "#009639",
    canonical: "https://hexmos.com/freedevtools/c/nginx/",
    keywords: ["nginx", "web server", "configuration", "cheatsheet"],
    features: ["Nginx config", "Reverse proxy", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "node": {
    title: "Node.js Cheatsheet | Online Free DevTools",
    name: "Node.js",
    path: "/freedevtools/c/node/",
    description: "Quick reference for Node.js runtime and npm commands.",
    category: "Developer Cheatsheets",
    icon: "🟢",
    themeColor: "#339933",
    canonical: "https://hexmos.com/freedevtools/c/node/",
    keywords: ["nodejs", "npm", "javascript", "cheatsheet"],
    features: ["Node.js commands", "npm", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "php": {
    title: "PHP Cheatsheet | Online Free DevTools",
    name: "PHP",
    path: "/freedevtools/c/php/",
    description: "Quick reference for PHP programming language syntax.",
    category: "Developer Cheatsheets",
    icon: "🐘",
    themeColor: "#777bb4",
    canonical: "https://hexmos.com/freedevtools/c/php/",
    keywords: ["php", "programming", "web development", "cheatsheet"],
    features: ["PHP syntax", "Functions", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "pm2": {
    title: "PM2 Cheatsheet | Online Free DevTools",
    name: "PM2",
    path: "/freedevtools/c/pm2/",
    description: "Quick reference for PM2 process manager commands.",
    category: "Developer Cheatsheets",
    icon: "⚡",
    themeColor: "#2b037a",
    canonical: "https://hexmos.com/freedevtools/c/pm2/",
    keywords: ["pm2", "process manager", "nodejs", "cheatsheet"],
    features: ["Process management", "Monitoring", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "puppeteer": {
    title: "Puppeteer Cheatsheet | Online Free DevTools",
    name: "Puppeteer",
    path: "/freedevtools/c/puppeteer/",
    description: "Quick reference for Puppeteer browser automation.",
    category: "Developer Cheatsheets",
    icon: "🎭",
    themeColor: "#40b5a4",
    canonical: "https://hexmos.com/freedevtools/c/puppeteer/",
    keywords: ["puppeteer", "automation", "testing", "cheatsheet"],
    features: ["Browser automation", "Testing", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "react": {
    title: "React Cheatsheet | Online Free DevTools",
    name: "React",
    path: "/freedevtools/c/react/",
    description: "Quick reference for React JavaScript library.",
    category: "Developer Cheatsheets",
    icon: "⚛️",
    themeColor: "#61dafb",
    canonical: "https://hexmos.com/freedevtools/c/react/",
    keywords: ["react", "javascript", "frontend", "cheatsheet"],
    features: ["React hooks", "Components", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "redis": {
    title: "Redis Cheatsheet | Online Free DevTools",
    name: "Redis",
    path: "/freedevtools/c/redis/",
    description: "Quick reference for Redis in-memory database commands.",
    category: "Developer Cheatsheets",
    icon: "🔴",
    themeColor: "#dc382d",
    canonical: "https://hexmos.com/freedevtools/c/redis/",
    keywords: ["redis", "database", "cache", "cheatsheet"],
    features: ["Redis commands", "Data structures", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "sails": {
    title: "Sails.js Cheatsheet | Online Free DevTools",
    name: "Sails.js",
    path: "/freedevtools/c/sails/",
    description: "Quick reference for Sails.js MVC framework commands.",
    category: "Developer Cheatsheets",
    icon: "⛵",
    themeColor: "#1e1e1e",
    canonical: "https://hexmos.com/freedevtools/c/sails/",
    keywords: ["sails", "nodejs", "mvc", "cheatsheet"],
    features: ["Sails commands", "MVC patterns", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "tailwind": {
    title: "Tailwind CSS Cheatsheet | Online Free DevTools",
    name: "Tailwind CSS",
    path: "/freedevtools/c/tailwind/",
    description: "Quick reference for Tailwind CSS utility classes.",
    category: "Developer Cheatsheets",
    icon: "🎨",
    themeColor: "#06b6d4",
    canonical: "https://hexmos.com/freedevtools/c/tailwind/",
    keywords: ["tailwind", "css", "utility classes", "cheatsheet"],
    features: ["Utility classes", "Responsive design", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "ubuntu": {
    title: "Ubuntu Cheatsheet | Online Free DevTools",
    name: "Ubuntu",
    path: "/freedevtools/c/ubuntu/",
    description: "Quick reference for Ubuntu Linux commands and shortcuts.",
    category: "Developer Cheatsheets",
    icon: "🐧",
    themeColor: "#e95420",
    canonical: "https://hexmos.com/freedevtools/c/ubuntu/",
    keywords: ["ubuntu", "linux", "terminal", "cheatsheet"],
    features: ["Linux commands", "Package management", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "vim": {
    title: "Vim Cheatsheet | Online Free DevTools",
    name: "Vim",
    path: "/freedevtools/c/vim/",
    description: "Quick reference for Vim text editor commands and shortcuts.",
    category: "Developer Cheatsheets",
    icon: "📝",
    themeColor: "#019733",
    canonical: "https://hexmos.com/freedevtools/c/vim/",
    keywords: ["vim", "text editor", "shortcuts", "cheatsheet"],
    features: ["Vim commands", "Modal editing", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "vue": {
    title: "Vue.js Cheatsheet | Online Free DevTools",
    name: "Vue.js",
    path: "/freedevtools/c/vue/",
    description: "Quick reference for Vue.js JavaScript framework.",
    category: "Developer Cheatsheets",
    icon: "💚",
    themeColor: "#4fc08d",
    canonical: "https://hexmos.com/freedevtools/c/vue/",
    keywords: ["vue", "javascript", "frontend", "cheatsheet"],
    features: ["Vue components", "Directives", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
  "xcode": {
    title: "Xcode Cheatsheet | Online Free DevTools",
    name: "Xcode",
    path: "/freedevtools/c/xcode/",
    description: "Quick reference for Xcode IDE shortcuts and features.",
    category: "Developer Cheatsheets",
    icon: "🔨",
    themeColor: "#147efb",
    canonical: "https://hexmos.com/freedevtools/c/xcode/",
    keywords: ["xcode", "ide", "ios development", "cheatsheet"],
    features: ["Xcode shortcuts", "iOS development", "Quick reference"],
    ogImage: "/freedevtools/free_devtools_banner.png",
    twitterImage: "/freedevtools/free_devtools_banner.png",
  },
};

export function getCheatSheetByKey(key: string): CheatSheet | undefined {
  return CHEATSHEETS_CONFIG[key];
}

export function getAllCheatSheets(): CheatSheet[] {
  return Object.values(CHEATSHEETS_CONFIG);
}

export function getAllUniqueCheatSheets(): CheatSheet[] {
  return getAllCheatSheets().filter((item) => !item.variationOf);
}

export function getCheatSheetsByCategory(category: string): CheatSheet[] {
  return getAllCheatSheets().filter((item) => item.category === category);
}


